//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntojitosWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_FACTURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEST_FACTURA()
        {
            this.TEST_FACTURA_DETALLE = new HashSet<TEST_FACTURA_DETALLE>();
        }
    
        public decimal IdFactura { get; set; }
        public decimal IdCliente { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public decimal ValorTotal { get; set; }
    
        public virtual TEST_CLIENTE TEST_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEST_FACTURA_DETALLE> TEST_FACTURA_DETALLE { get; set; }

        public TEST_FACTURA(FacturaModel factura)
        {
            this.IdCliente = factura.IdCliente;
            this.FechaVenta = factura.FechaVenta;
            this.ValorTotal = factura.ValorTotal;
        }
    }
}
