//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntojitosWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_FACTURA_DETALLE
    {
        public decimal IdFacturaDetalle { get; set; }
        public decimal IdFactura { get; set; }
        public decimal IdProducto { get; set; }
        public int Cantidad { get; set; }
        public decimal ValorUnidad { get; set; }
        public decimal ValorTotal { get; set; }
    
        public virtual TEST_FACTURA TEST_FACTURA { get; set; }
        public virtual TEST_PRODUCTO TEST_PRODUCTO { get; set; }

        public TEST_FACTURA_DETALLE(FacDetalleModel detalle)
        {
            //this.IdFacturaDetalle = detalle.IdFacturaDetalle;
            this.IdFactura = detalle.IdFactura;
            this.IdProducto = detalle.IdProducto;
            this.Cantidad = detalle.Cantidad;
            this.ValorUnidad = detalle.ValorUnidad;
            this.ValorTotal = detalle.ValorTotal;
        }
    }
}
